services:
  app:
    build: .
    container_name: image_server_app
    restart: unless-stopped
    volumes:
      - ./images:/app/images
      - ./logs:/app/logs
    expose:
      - "8000"
    environment:
      - PYTHONUNBUFFERED=1

  nginx:
    image: nginx:1.27
    container_name: image_server_nginx
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./images:/images:ro
    ports:
      - "8080:80"
      - "80:80"
    restart: unless-stopped
volumes:
  images:
  logs: